Repository isodate/isodate, pull requests merged in 2021-11, with the labels that each got.

#4 Drop support for EOL Python 2.7 and 3.4-3.5
  .gitignore
  .pre-commit-config.yaml
  setup.cfg
  setup.py
  src/isodate/duration.py
  src/isodate/isoduration.py
  src/isodate/tests/__init__.py
  src/isodate/tests/test_date.py
  src/isodate/tests/test_datetime.py
  src/isodate/tests/test_duration.py
  src/isodate/tests/test_pickle.py
  src/isodate/tests/test_strf.py
  src/isodate/tests/test_time.py
  tests/__init__.py
  tests/test_date.py
  tests/test_datetime.py
  tests/test_duration.py
  tests/test_pickle.py
  tests/test_strf.py
  tests/test_time.py
  tox.ini
Labels: changelog: Removed

#5 Format with Black and isort
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  setup.cfg
  setup.py
  src/isodate/__init__.py
  src/isodate/duration.py
  src/isodate/isodates.py
  src/isodate/isodatetime.py
  src/isodate/isoduration.py
  src/isodate/isoerror.py
  src/isodate/isostrf.py
  src/isodate/isotime.py
  src/isodate/isotzinfo.py
  src/isodate/tzinfo.py
  tests/test_date.py
  tests/test_datetime.py
  tests/test_duration.py
  tests/test_pickle.py
  tests/test_strf.py
  tests/test_time.py
Labels: changelog: Changed

#6 Use setuptools_scm for auto-versioning from Git tags
  .github/workflows/deploy.yml
  setup.cfg
  setup.py
Labels: changelog: Added

#7 Refactor: 'import datetime as dt' for clarity
  src/isodate/isodatetime.py
  tests/test_datetime.py
  tests/test_duration.py
  tests/test_strf.py
Labels: changelog: Changed

#8 Docs: Mention isoduration
  README.md
Labels: changelog: skip

#9 Document release checklist
  RELEASING.md
Labels: changelog: skip

#10 Add __version__
  setup.cfg
  src/isodate/__init__.py
Labels: changelog: Added

#11 Add LICENSE.md file
  LICENSE.md
  setup.cfg
Labels: changelog: Added

#12 Fix deploy username
  .github/workflows/deploy.yml
Labels: changelog: Fixed
